### ISSUE TITLE
[MODULE_NOT_FOUND] Error Plugin: @mainframe/cli: Cannot find module '@mainframe/app-manifest'

### ISSUE THREAD

**Issue by Robsonsjre** [MainframeHQ/mainframe-os#377]
### Description
Im using linux and trying to compile and run Mainframe OS from source following this [instructions](https://docs.mainframe.com/docs/platform) and after running:

 `packages/cli/bin/run env:create` 

it shows the error: 

`[MODULE_NOT_FOUND] Error Plugin: @mainframe/cli: Cannot find module '@mainframe/app-manifest'`
### How to Reproduce

1. Use linux, compile and run from source
2. `git clone https://github.com/MainframeHQ/mainframe-os.git`
3. `cd mainframe-os`
4. `git checkout release-v0.2`
5. `yarn install in the root`
6. `yarn install` in each packages/folder
7.   `packages/cli/bin/run env:create` 

### Enviroment
````
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
Node version: 10.15.3
Npm version: 6.4.1
````

**Comment by mosic** [comment]
Hi Rob, instead of running `yarn install` in each package dir, just run `yarn build` in the root and that should handle everything for you.

**Comment by Robsonsjre** [comment]
Hi @mosic, when I run `yarn build`it throws an error showing that some modules are missing inside the packages folder

 `lerna ERR! npm run build stderr: sh: 1: webpack: not found`

![mainframe_4](https://user-images.githubusercontent.com/11945073/54769108-dfcd5e80-4c00-11e9-9983-ee3b3edb3226.png)

**Comment by mosic** [comment]
It might be because of your step 6, so there's now a conflict with what `yarn build` is trying to do. Can you try deleting the whole directory and cloning the repo again?

**Comment by Robsonsjre** [comment]
that was already a new one, hehe

**Comment by Robsonsjre** [comment]
Well, solved with an ugly workaround:
I copied `/packages/app-manifest` and `/packages/app-permissions` to `/packages/cli/node_modules/@mainframe`

**Comment by Robsonsjre** [comment]
Found a better solution for this issue and the #379:
after `yarn install` and before `yarn build`, just do a `yarn bootstrap` and `lerna` will handle all dependencies!
