### ISSUE TITLE
App crashes on macos

### ISSUE THREAD

**Issue by flexsurfer** [MainframeHQ/mainframe-os#416]
1) Download and install https://download.mainframeos.com/os/releases/MainframeOS.dmg
2) run on macos 10.14.4 
3) 
![image](https://user-images.githubusercontent.com/11790366/56185052-9bc15400-601c-11e9-8b4c-b73d50a08247.png)

**Comment by walkamongus** [comment]
For anyone hitting this issue -- check your Python version. I had Python 3 as my default (via homebrew) and this caused syntax errors such as the following with the setup script:

```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/opt/python/libexec/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
```
Rolling this back to Python 2 allowed the script to complete and I'm now able to open mainframeOS without error.

**Comment by PaulLeCam** [comment]
Thanks for reporting this issue, it should be fixed in the latest release.
