### ISSUE TITLE
Unable to download/install dApps

### ISSUE THREAD

**Issue by canadaduane** [MainframeHQ/mainframe-os#427]
After creating a new password & new wallet, I tried downloading/installing a mainframe dApp ("CDP Pro"). There was an error message (something like "unable to download" in red) and then when I switched back to the `Applications` tab, the app is shown as installed, but clicking on it opens a blank window.

I tried to install a 2nd app ("uniswap" this time) and the main window seems to be in a "forever loading" state, with mainframe logo spinner spinning. When I click away from `Applications` and then go back, it shows a spinner on top of the "uniswap" logo, but no spinner on "CDP Pro."

Neither dApp seems to work (but each fails in a different way).

_Possibly related context:_ I installed version 0.2 of Mainframe OS as soon as it came out, but did not install any apps at that time. I recently installed 0.3.

**Comment by howleysv** [comment]
Thanks @canadaduane!

We have had a few teething issues with the reliability of our swarm gateway, but our next point release should address this.

**Comment by howleysv** [comment]
Should be working now as of v0.3.1
